travis:
  secure:
    BINSTAR_TOKEN: FzI8hr8gegAKPl15qd92T4LgUY7Mz+SIIJ8DIprWImjdlk74JEcCPrD4bkQhd1UqcHsBa0Df4fIa5JI4d20tGjajJvq2gNiJmXZhWLcCvb6wgksAr2HlcnoXcwYq1wW+SnGR/XXQuxh7/Ya3229vSPYi+RA8Azn06G+Js88bT4p+9mCLsDQpslbKLm69FyUvSbGwmPjo7Hgaoux2ihySO5YN2NEYYHzGkixuNGf45Yi5zKwGBFXp9dXvSC6g8SwTRomYOQIwYal9wv220vOHnF2WZoAKsLFaleJx8tjqi10Yp5tA7zheBi4zUd5T+7RKug+Tns3j2xqybhrc2mYHMH0/FYo8FWUdv7A/1appj1Oum3clNedKsdM25Hzs5Tl0mm5KyLRO4tri64IpxfnOVevJAjivM7HMrXE5v6D3i4ZovDaiQFNPsmFKceLYo4RVNV0bi3W0JLbAuipy8Lx9Bmt/0VaFZIpQBu6FLkKn4Hd+z6/QXSV+o8AwKgjqiuKaGRBTRL9W9YNhT6MQNpK4GdDHo7tGdaAnBVXfAZTdwjdUYZPi/oLz6SU+2UJtYF0ELNhehlvVF7FXZGUnWFVvtDlu5yr0V1cflYJjE/Scxrt8d0LHXRpQ3XvulLEUlvCqr6FutMoNgoPc3+i34EhWQUmD3AB415jIT07W567GjqM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
