travis:
  secure:
    BINSTAR_TOKEN: hM/krXIoB5x6ish66wIwx2NN6oAw9iXxo9+1czH/N+tZpeteLtrPcF3NXhDYqFLS3cUMgb5l56euYqm1IphOxBqGyLJUk1XscMWTkd9jKioX3M5AvuNp9Eh8ITL1n0wwN7ZUIfoax6UncWMSVAsRDpzvNJsl/wp7mDDhjVsKIHZJ/3UWvN7OMZN78XDInr7fRQyc1CvV4xZK0qNBN2ku4698+glM+C7qeFHkTj1oc5s7r0sMHG3I5SzdnBMLVKBaWq0x3qUebRq4+AqPQXn20/IervZtmQRlCnKKC44/bPB/h7YIMSxIgxYrdiBKcJ2EFavHqFhKDa4ROwrMbSjpoddAIzFuAUtTz+SQTCFPHQ2qzbl/xV3D/FaJn5taaMyyC0R5NVsS+MhPmu3EqaB14WlP+Ez57RoUyEkmZCzswTGRDpEvMOnt8oEMb8u0xlSIdBMxKFKwLmTEeAQJBP06UvmEzHEGX5IE1RJDPMxAOMA2JwCCcnuQgXgOM4NFIPPwhWwE+a6voxwHVDxG35j/SpYC5KA9In10xlDLSbZH8cNlJIRsgwm0TWGwtEU72QbDRkD5lU+d8eAfKHaqVsRZBC26SW1P0G9FI5wulh33jxF7IIizEqjLRtVXM71hBmotdhRM/IAhpnFZZvL/QV8cgDeuekUkaFHVQHs2aglwEho=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
